server:
  port: 8080
  context-path: /hongw

spring:
  mvc:
    static-path-pattern: /static/**

  datasource:
    url: jdbc:mysql://47.101.142.113:3306/myManager?serverTimezone=UTC
    username: root
    password: ad654790252
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql

  freemarker:
    suffix: .ftl




